### PR TITLE
Weather App Project

### PR DESCRIPTION
**Pull request by necmigunduz**
In this project, I did;
- Create an application providing information for a selected location with a city name or a country name;
- Use HTML5, CSS3, Webpack, Bootstrap, Google Fonts, and JS.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Good code structure.
- Simple and understandable design.
## However, there are some changes required 👀 🧰 🔨 🔧
- I couldn't really test the complete feature set of your app because the API call fails when I try to query a city name. Please change the URL to `https://...` so that the request is done through `HTTPS`
image
- Please make sure to add a `dev` option to your `package.json`
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
***[OPTIONAL]***

- You may add an auto-location method to automatically display the user's current weather on page load.
### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the changes requested. 
Let's make some change(s) before merging this PR.
- [x] fix failing linter errors

### Martin Afani
#### Slack: whiz25

**Comment by necmigunduz** [comment]
I have just fixed it. Thank you!

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Necmi Gunduz** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to fix before you can go ahead:

- [x] kindly use the most recent version of the linters.yml file for JavaScript (remember not to edit it): [JavaScript Linters](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by necmigunduz** [comment]
I have replace the linters.yml with the latest version.

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous reviews.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Comment by necmigunduz** [comment]
Thank you all! :)

**Pull request merged**
